### ISSUE TITLE
Падает сборка при деплое в heroku

### ISSUE THREAD

**Issue by amd-9** [Hexlet/hexlet-cv#234]
При попытке деплоя в heroлг (make deploy) билд падает с ошибкой.

Сначала упал с 

```
-----> Installing node-v12.16.2-linux-x64
-----> Installing yarn-v1.22.4
-----> Detecting rake tasks
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       yarn install v1.22.4
       [1/4] Resolving packages...
       error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
       info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
       Compiling...
       Compilation failed:
       yarn run v1.22.4
       info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
       
       
       error Command "webpack" not found.
       
 !
 !     Precompiling assets failed.
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed

```
Пофиксил прогнав `yarn instal`l и закомитив `yarn.lock` файл. Затем упал на этапе сборки модулей

```
       [119] ./app/javascript/entrypoints/application.scss 562 bytes {0} [built] [failed] [1 error]
       [120] ./node_modules/bootstrap/dist/js/bootstrap.esm.js + 55 modules 237 KiB {0} [built]
             |    56 modules
           + 116 hidden modules
       
       ERROR in ./node_modules/bootstrap-icons/font/bootstrap-icons.css
       Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
       ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
       TypeError: this.getOptions is not a function
           at Object.loader (/tmp/build_0e5cb90e/node_modules/postcss-loader/dist/index.js:40:24)
           at /tmp/build_0e5cb90e/node_modules/webpack/lib/NormalModule.js:316:20
           at /tmp/build_0e5cb90e/node_modules/loader-runner/lib/LoaderRunner.js:367:11
           at /tmp/build_0e5cb90e/node_modules/loader-runner/lib/LoaderRunner.js:233:18
        @ ./app/javascript/entrypoints/application.js 6:0-49
        @ multi ./app/javascript/entrypoints/application.js ./app/javascript/entrypoints/application.scss
       
       ERROR in ./app/javascript/entrypoints/application.scss
       Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
       ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
       TypeError: this.getOptions is not a function
           at Object.loader (/tmp/build_0e5cb90e/node_modules/sass-loader/dist/index.js:25:24)
           at /tmp/build_0e5cb90e/node_modules/webpack/lib/NormalModule.js:316:20
```

Пофиксил даунгрейдом зависимости `postcss-loader`

```
     "popper.js": "^1.16.1",
-    "postcss-loader": "^6.1.1",
+    "postcss-loader": "^4.2.0",
     "prop-types": "^15.7.2",
```

**Comment by mokevnin** [comment]
fixed
